version: "3.7"

# Setting network for the two containers
networks:
  kong-net:
   driver: bridge
   name: kong-network 

services:
  # Kong service and starter command
  kong:
    container_name: kong
    image: kong
    networks:
      - kong-net
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_LOG_LEVEL: debug
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl, 0.0.0.0:9080 http2, 0.0.0.0:9081 http2 ssl
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 120s
      timeout: 10s
      retries: 3
    volumes:   
    - ./compose/kong/:/usr/local/kong/declarative       
    ports:
      - "8001:8001"
      - "8444:8444"
      - "8000:8000"
      - "8443:8443"
      - "9080:9080"
      - "9081:9081"

  # Node server running ower app
  node_server:
    image: 'node:20'
    container_name: am-app
    networks:
      - kong-net
    working_dir: '/src'
    command: ['npm', 'run', 'start_local']
    volumes:
      - ./:/src